use_frameworks!

platform :ios, '13.0'

target 'Components_Example' do
  pod 'Components', :path => '../'

  target 'Components_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
